//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutedMission
    {
        public int ID { get; set; }
        public Nullable<int> MissionTemplateID { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public Nullable<int> ExecutedBy { get; set; }
    
        public virtual MissionPlan MissionPlan { get; set; }
    }
}
