//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGeneratorService.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutedStep
    {
        public ExecutedStep()
        {
            this.ExecutedStepStatuses = new HashSet<ExecutedStepStatus>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ExecutedMissionID { get; set; }
        public Nullable<int> StepID { get; set; }
    
        public virtual Step Step { get; set; }
        public virtual ICollection<ExecutedStepStatus> ExecutedStepStatuses { get; set; }
    }
}
